models/Articulos.php
<?php

namespace app\models;
use yii\web\UploadedFile;
use Yii;

/**
 * This is the model class for table "articulos".
 *
 * @property integer $id
 * @property string $articulo
 * @property string $subtitulo
 * @property string $foto1
 * @property string $foto2
 * @property string $estado
 * @property integer $ventas
 * @property integer $stock
 * @property double $precio
 * @property string $tipopago
 * @property integer $id_usu
 * @property string $descripcion
 * @property string $garantia
 * @property string $tipopublicacion
 * @property string $fechaexp
 * @property string $fechainc
 * @property integer $id_cat
 *
 * @property Categorias $idCat
 * @property User $idUsu
 */
class Articulos extends \yii\db\ActiveRecord
{
    // public $file;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'articulos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

/*
 ['file', 'file','skipOnEmpty' => false,
       'uploadRequired' => 'No has seleccionado ningún archivo', //Error
       'maxSize' => 1024*1024*1, //1 MB
       'tooBig' => 'El tamaño máximo permitido es 1MB', //Error
       'minSize' => 10, //10 Bytes
       'tooSmall' => 'El tamaño mínimo permitido son 10 BYTES', //Error
       // 'extensions' => 'pdf, txt, doc',
       'wrongExtension' => 'El archivo {file} no contiene una extensión permitida {extensions}', //Error
       'maxFiles' => 4,
       'tooMany' => 'El máximo de archivos permitidos son {limit}', //Error
       ],*/
            [['articulo', 'estado', 'stock', 'precio', 'garantia',  'id_cat'], 'required','message'=>'{attribute} no puede estar en blanco .'],
            [['subtitulo', 'descripcion'], 'string'],
            [['ventas', 'stock', 'id_usu', 'id_cat'], 'integer'],
            [['fechaexp', 'fechainc','foto1'], 'safe'],
            [['articulo', 'estado', 'tipopago', 'tipopublicacion'], 'string', 'max' => 255],
            [['garantia'], 'string', 'max' => 30],
            [['id_cat'], 'exist', 'skipOnError' => true, 'targetClass' => Categorias::className(), 'targetAttribute' => ['id_cat' => 'id']],
            [['id_usu'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_usu' => 'id']],
            [['foto1'], 'file', 'extensions' => 'png, jpg'],

             // [['foto1'], 'safe'],
            // [['foto1'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'articulo' => Yii::t('app', 'Articulo'),
            'subtitulo' => Yii::t('app', 'Subtitulo'),
            'foto1' => Yii::t('app', 'Foto1'),
            'foto2' => Yii::t('app', 'Foto2'),
            'estado' => Yii::t('app', 'Estado'),
            'ventas' => Yii::t('app', 'Ventas'),
            'stock' => Yii::t('app', 'Stock'),
            'precio' => Yii::t('app', 'Precio'),
            'tipopago' => Yii::t('app', 'Tipopago'),
            'id_usu' => Yii::t('app', 'Id Usu'),
            'descripcion' => Yii::t('app', 'Descripcion'),
            'garantia' => Yii::t('app', 'Garantia'),
            'tipopublicacion' => Yii::t('app', 'Tipopublicacion'),
            'fechaexp' => Yii::t('app', 'Fechaexp'),
            'fechainc' => Yii::t('app', 'Fechainc'),
            'id_cat' => Yii::t('app', 'Id Cat'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCat()
    {
        return $this->hasOne(Categorias::className(), ['id' => 'id_cat']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUsu()
    {
        return $this->hasOne(User::className(), ['id' => 'id_usu']);
    }

        public function beforeSave($insert)
            {
                if (parent::beforeSave($insert)) {
                   if ($this->isNewRecord) {
                       // $this->articulo= "nuevo";
                       $this->id_usu=Yii::$app->user->identity->getId();
                       $this->ventas=0;
                      
                   }

                    return true;
                } else {
                    return false;
                }
             }   

     public function upload()
    {

        // if ($this->isNewRecord) {

            if ($this->validate()) {
                $rnd= rand(0,9999);
                // $rnd = 2;
                $this->foto1->saveAs('images/articulos/'.$rnd.$this->foto1->baseName . '.' . $this->foto1->extension);
                 $this->foto1= $rnd.$this->foto1->name;
                return true;
            } else {
                return false;
            }
        // }

        // else {

        // }
    }
     public function upload2()
    {
        if ($this->validate()) {
            $rnd= rand(0,9999);
            $this->foto2->saveAs('images/articulos/'.$rnd.$this->foto2->baseName . '.' . $this->foto2->extension);
             $this->foto2= $rnd.$this->foto2->name;
             return true;
        } else {
            return false;
        }
    }
}

controllers/ArticulosController.php
<?php

namespace app\controllers;
use yii\data\Pagination;

use Yii;
use app\models\Articulos;
use app\models\Preguntas;
use app\models\PreguntasQuery;
use app\models\ArticulosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Categorias;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

// use yii\base\InvalidParamException;
// use yii\web\BadRequestHttpException;
// use yii\data\Pagination;
// use yii\data\ActiveDataProvider
/**
 * ArticulosController implements the CRUD actions for Articulos model.
 */
class ArticulosController extends Controller
{
    public function behaviors()
    {
        return [

        'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'index','preguntas'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['create','index','preguntas','update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [ 'actions' => ['update'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            // $model = new Articulos;
                            $id = $_GET['id'];
                            // $id = $_GET['id'];
                            $model = $this->findModel($id);
              if (Yii::$app->user->isGuest) {
                              return false;
                            }
                            // return Yii::$app->user->identity->getId() == $model->id_usu;
                            return Yii::$app->user->identity->getId() == $model->id_usu;
                        }
                        ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Articulos models.
     * @return mixed
     */
    public function actionIndex()
    {
          $categories = Categorias::find()->select(['id', 'categoria'])->where(['padre' => 0,])->all();
        $query = Articulos::find()->where(['id_usu' => Yii::$app->user->identity->getId()]);
        if (isset($_GET['cat'])) { $query = Articulos::find()->where(['id_cat' => $_GET['cat'], 'id_usu' => Yii::$app->user->identity->getId()]); }
 
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize'=>6]);

        $models = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('index', [
            'categories'=> $categories, 
                                'models'=> $models, 
                                'pages' => $pages
        ]);
    }

    /**
     * Displays a single Articulos model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    { $preguntas= new Preguntas;
      $mpreguntas = Preguntas::find()->where(['id_art' => $_GET['id'],])->all(); 
        // $preguntas->save();
        
        // var_dump($_POST) ;
        if ($preguntas->load(Yii::$app->request->post()) && $preguntas->save() && $preguntas->validate()) {
          Controller::refresh();
        }
        return $this->render('view', [ 'model' => $this->findModel($id), 'preguntas' => $preguntas, 'mpreguntas' => $mpreguntas,
        ]);

    }

    public function actionCreate()
    {   
        $model = new Articulos();
        $categorias = Categorias::find()->asArray()->all();
        $categoria = ArrayHelper::map($categorias, 'id', 'categoria');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->foto1 = UploadedFile::getInstance($model,'foto1')) { if ($model->upload()) { $model->save(); }
                }
          if ($model->foto2 = UploadedFile::getInstance($model,'foto2')) { if ($model->upload2()) { $model->save(); }
                }
            return $this->redirect(['view', 'id' => $model->id]); }
         else {
            return $this->render('create', [
                'model' => $model,
                'categoria'=>$categoria,
            ]);
        }
    }
    /**
     * Creates a new Articulos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

// SELECT * FROM preguntas as P  INNER JOIN articulos as A ON P.id_art = A.id  INNER JOIN user as U ON A.id_usu = U.id WHERE P.id_art = A.id

//SELECT U.username, P.post, C.comment FROM comentarios as C  INNER JOIN post as P ON C.idpost = P.idpost  INNER JOIN usuarios as U ON P.id_usu = U.id WHERE C.idpost = P.idpost



// SELECT c.preguntas, p.articulos, r.user FROM preguntas cINNERJOIN articulos pON c.id = p.id_art INNER JOIN usuarios r ON r.Id = p.id_usu
//SELECT c.comuna, p.provincia, r.region FROM Comunas cINNER JOIN Provincias pON c.idprovincia= p.idprovincia INNER JOIN Regiones r ON r.IdRegion = p.IdRegion
      // $misarticulos = Articulos::find()->select('id')->where(['id_usu' =>Yii::$app->user->identity->getId()])->orderBy('id')->all(); 
      public function actionPreguntas()    { 
      $preguntas = new Preguntas;
// echo "<br><br><br><br><br>";
      // var_dump($_POST['Preguntas']);

      if (isset($_POST['Preguntas'])) {
$model = $this->findPreguntas($_POST['Preguntas']['id']);
            // $model = Preguntas::find($_POST['Preguntas']['id']);
            $model->respuesta = $_POST['Preguntas']['respuesta'];
            $model->save();  
      }
$my=Preguntas::findBySql('select P.id, P.pregunta, P.respuesta from preguntas as P INNER JOIN articulos as A ON P.id_art = A.id where respuesta IS NULL AND id_usu ='.Yii::$app->user->identity->getId())->all();

        return $this->render('preguntas', [
                                // 'mpreguntas'=> $mpreguntas, 
                                'preguntas' => $preguntas,
                                'my' => $my,
        ]);
    }

    /**
     * Updates an existing Articulos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $categorias = Categorias::find()->asArray()->all();
        $categoria = ArrayHelper::map($categorias, 'id', 'categoria');
        $model = $this->findModel($id);
        echo "<br><br><br><br>";

        if (!empty($_POST)) {
          $file = \yii\web\UploadedFile::getInstance($model, 'foto1');
          if ($model->save()) {
              if ($file==null) {
              $fotoa = $model->foto1;
               $model->load(Yii::$app->request->post());
              $model->foto1 =$fotoa;
               $model->save();
            }
            else {
               $model->load(Yii::$app->request->post());
                $rnd= rand(0,9999);
                // $model->foto1 = $rnd.$_POST['Articulos']['foto1'];
              $model->foto1= $rnd.$file->name;
              $model->save();
              $file->saveAs('images/articulos/'.$rnd.$file->name);
              }
            }
          return $this->redirect(['view', 'id' => $model->id]);
        }
        // its better if you relegate such a code to your model class
    // }
    return $this->render('update', ['model'=>$model, 'categoria' => $categoria]);
    }

    /**
     * Deletes an existing Articulos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Articulos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Articulos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Articulos::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
      protected function findPreguntas($id)
    {
        if (($model = Preguntas::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/articulos/_form.php
<?php

use kartik\widgets\FileInput;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use kartik\widgets\ActiveForm;

use yii\helpers\Html;
// use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;
/* @var $this yii\web\View */
/* @var $model frontend\models\Articulos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="articulos-form">
<div class="col-md-3"> </div>
    <?php // $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <?php $form = ActiveForm::begin(["method" => "post",
         "enableClientValidation" => true,
         "options" => ["enctype" => "multipart/form-data", 'class'=>'col-md-6'],
         ]);
    ?>
    <?php   

     // echo Html::activeLabel($model,'fieldname'); //label
        // echo Html::activeTextInput($model, 'fieldname'); //Field
        // echo Html::error($model,'fieldname', ['class' => 'help-block']);

         ?>
    <?= $form->field($model, 'id_cat')->dropDownList($categoria,['prompt'=>'Seleccione una categoria']); ?>
<?= $form->field($model, 'articulo')->textInput(['maxlength' => true]) ?>
    <div class="form-group field-articulos-stock required has-error">   
    <?php 
  // echo Html::activeLabel($model,'articulo'); //label
  //       echo Html::activeTextInput($model, 'articulo'); //Field
  //       echo Html::error($model,'articulo', []);



    $form->field($model, 'articulo')->textInput(['maxlength' => true],['class'=>'col-md-6']) ?>
    </div>
    
<?php 
echo FileInput::widget([ 
'model' => $model, 
'attribute' => 'foto1', 
'options' => ['multiple' => false],
 'pluginOptions' => [   'showUpload' => false,  'browseLabel' => '',
        'removeLabel' => '','initialPreview'=>[ Html::img("images/articulos/".$model->foto1,
 ['class'=>'file-preview-image', 'alt'=>'Adjuntar Foto', 'title'=>'Adjuntar Foto']), ], 'initialCaption'=>$model->articulo,] ]); 

 ?>
    
<?= $form->field($model, 'descripcion')->widget(CKEditor::className(), [        'options' => ['rows' => 6],         
  'preset' => 'standard',  
'clientOptions' => []     ]) ?>


    <!-- </div> -->
    <?= $form->field($model, 'estado')->radioList(array(123=>'Nuevo',1231=>'Usado')); ?>
    <?php echo $form->field($model, 'precio')->input('number',['step'=>"0.01"]); ?>
    <?= $form->field($model, 'stock')->textInput() ?>
    <?php // $form->field($model, 'tipopago')->textInput(['maxlength' => true]) ?>
    <?php // $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>

<?php ?>




    <?= $form->field($model, 'garantia')->textInput(['maxlength' => true]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-lg btn-info' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div> 
<div class="row"></div>

views/articulos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\ArticulosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="articulos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'articulo') ?>

    <?= $form->field($model, 'subtitulo') ?>

    <?= $form->field($model, 'foto1') ?>

    <?= $form->field($model, 'foto2') ?>

    <?php // echo $form->field($model, 'estado') ?>

    <?php // echo $form->field($model, 'ventas') ?>

    <?php // echo $form->field($model, 'stock') ?>

    <?php // echo $form->field($model, 'precio') ?>

    <?php // echo $form->field($model, 'tipopago') ?>

    <?php // echo $form->field($model, 'id_usu') ?>

    <?php // echo $form->field($model, 'descripcion') ?>

    <?php // echo $form->field($model, 'garantia') ?>

    <?php // echo $form->field($model, 'tipopublicacion') ?>

    <?php // echo $form->field($model, 'fechaexp') ?>

    <?php // echo $form->field($model, 'fechainc') ?>

    <?php // echo $form->field($model, 'id_cat') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/articulos/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Articulos */

$this->title = Yii::t('app', 'Create Articulos');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Articulos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="articulos-create">

    <h1 class="titulocrear"><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categoria'=>$categoria,
    ]) ?>

</div>

views/articulos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\LinkPager;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\ArticulosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Mis Articulos');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="articulos-index">


    <h1 class="articulos-create impact text-center"><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="text-center">
        <?= Html::a(Yii::t('app', 'Vender'), ['create'], ['class' => 'btn btn-info']) ?>
    </p>
    <div class="row">
        <div class="col-sm-3 col-md-3 sidebar"> 
            <?= "<ul class='categoriasinicio'>"; ?>
            <?php  foreach ($categories as $key => $value){
                ?> 
                <li><a href=" <?=  Url::to(['articulos/index', 'cat' => $value['id']]) ?>"> <?= $value['categoria']; ?>
                </a></li> <?php } echo "</ul>";
                 ?>  

        </div>
        <div class="col-sm-9 col-md-9 "> 
            <!-- <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">  -->

            <div class="row">
            <?php if (!count($models)): ?>
                no hay articulos
            <?php endif ?>
            <?php foreach ($models as $model) :?>
                    <div class="col-md-4 articulo"> 
                        <?php if (!$model->foto1): ?>
                        <div class="art_foto1">  
                        <?= Html::img('@web/images/sinfoto.png',['width'=>'100%','height'=>'100%','title'=>$model->articulo]);?>
                        </div>
                        <?php else: ?>
                        <div class="art_foto1"> 
                           <?= Html::img('@web/images/articulos/'.$model->foto1,['width'=>'100%','height'=>'100%','title'=>$model->articulo]);?>
                        </div>
                         <?php endif ?>
                        <div class="art_articulo"><?php echo $model->articulo;?></div>
                        <div class="art_precio"><?php echo $model->precio." Bs"; ?></div>
                        <?= Html::a("<i class = 'editart glyphicon glyphicon-pencil'></i>", ['update', 'id' => $model->id]) ?>
                        <?= Html::a("<i class = 'verart glyphicon glyphicon-eye-open'></i>", ['view', 'id' => $model->id]) ?>       
                        <?= Html::a("", ['articulos/delete', 'id'=>$model->id], [ 'class' => 'verelim glyphicon glyphicon-trash', 'data' => [ 'confirm' => "Estas Seguro que deseas Eliminar Este articulo, Esta Accion no se puede deshacer?", 'method' => 'post', ], ]); ?>
                    </div>
                       
            <?php endforeach; ?>
            </div>
            <div class="row">
                <div class="col-md-12 paginacion" style="text-align: center;">
                    <?php echo LinkPager::widget(['pagination' => $pages,]);?>
                </div>

            </div>


    </div>
</div>
</div>

views/articulos/view.php
<?php
use app\models\Preguntas;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model frontend\models\Articulos */

$this->title = $model->articulo;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Articulos'), 'url' => ['index']];

$this->params['breadcrumbs'][] = 

['label' => $model->getIdCat()->one()->categoria, 'url' => ['site/index', 'cat' => $model->id_cat]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="articulos-view">
    <div class="row">
        <div class="col-md-3 text-right"> 
       <?php if (!isset($model)): ?>
           <?php if (Yii::$app->user->identity->getId() == $model->id_usu ): ?>
            <?php echo Html::a('<i class="glyphicon glyphicon-chevron-left iconback"></i>', ['articulos/index']) ?> 
            <?php endif ?>
       <?php endif ?>
        </div>
        <div class="col-md-6"> 
            <?php if (!$model->foto1): ?>
                <div class="art_foto1">  
                <?= Html::img('@web/images/sinfoto.png',['width'=>'100%','height'=>'100%','title'=>$model->articulo]);?>
                </div>
            <?php else: ?>
                <div class="art_foto1"> 
                <?= Html::img('@web/images/articulos/'.$model->foto1,['width'=>'100%','height'=>'100%','title'=>$model->articulo]);?>
                </div>
            <?php endif ?>                
            <div class="row art_usuario impact text-center"> <?= Html::a("Usuario: ".$model->getIdUsu()->one()->username, ['user/profile/show', 'id' => $model->id_usu], ['class' => '']) ?> </div>
            <div class="row articulo-descripciontitulo naranjamp"><?= "<h1>DESCRIPCION</h1>" ?></div>
            <div class="row"> <?= $model->descripcion ?> </div> 
            <div class="row articulo-preguntas naranjamp"> <h1>PREGUNTAS</h1></div>
            <div class="row formupreguntas">
                   <?php $form = ActiveForm::begin(["method" => "post", "enableClientValidation" => true, "options" => ["enctype" => "multipart/form-data", 'class'=>'col-md-12'],
                    ]);     ?> 
            <?= $form->field($preguntas, 'pregunta')->textInput(['maxlength' => true],['class'=>'col-md-6']);  ?>
            <div class="form-group articulo-formulario-pregunta">
                    <div class="col-lg-offset-1 col-lg-11 botonpreguntar">
                    <?php if (!Yii::$app->user->isGuest): ?>
                        <?php if(Yii::$app->user->identity->getId() != $model->id_usu): ?>
                        <?= Html::submitButton('Preguntar', ['class' => 'btn btn-info']) ?>
                        <?php else: ?>
                        <?= Html::submitButton('Preguntar', ['class' => 'btn btn-info', 'disabled' => true]) ?>
                        <?php endif; ?>
    <?php else: ?>
                    <?= "Para Preguntar debes Iniciar Sesion".Html::submitButton('Preguntar', ['class' => 'btn btn-info', 'disabled' => true]) ?>
<?php endif; ?>
                        
                    </div>
                </div> 
            <?php ActiveForm::end() ?>
            </div>  <!-- formupregunta 
            select(['id', 'categoria'])->-->
            <!-- </div> -->
            <div class="row cuadro-preugntas">
            <?php if (!$mpreguntas): ?>
                <div class="sinpreguntas">aun nadie hace preguntas... ¡Haz Tu la primera!</div>
                <?php else: ?>
                <?php foreach ($mpreguntas as $key => $value): ?>
                    
                    
                <div class="pregunta"> <span class="glyphicon glyphicon-shopping-cart"></span> <?php echo $value['pregunta'] ?></div>
                <div class="respuesta">
                <span class="glyphicon glyphicon glyphicon-user"></span>
                <?php if (is_null($value['respuesta'])): ?>
                     El vendedor aun no ha respondido
                 <?php else: ?>
                 <?= $value['respuesta'] ?>
                <?php endif ?>
                </div>
               
            <?php endforeach;?>

                <?php endif ?>
            </div>
        </div>
        <div class="col-md-3 articulo">   
            <h1 class="articulo-articulo"><?= Html::encode($this->title) ?></h1>
            <?php if (!Yii::$app->user->isGuest): ?>
                <?php if (Yii::$app->user->identity->getId() == $model->id_usu ): ?>
                <?php //echo Html::a("Editar mi Publicacion", Url::to(['update', 'id' => $model['id']])); ?>
                <?php endif ?>
            <?php endif ?>
                <div class="art_precio"><?php echo $model->precio." Bs"; ?></div>
                <div class="art_cantidad"><?php echo "Cant: ".$model->stock;?></div>
            <?php if (!isset($model)): ?> 
                <?php if (Yii::$app->user->identity->getId() != $model->id_usu ): ?><?php endif ?>
                <div class="art_comprar"> <?= Html::submitButton(Yii::t('app', 'buy'), ['class' => $model->isNewRecord ? 'disabled btn btn-lg btn-info' : 'btn btn-info']) ?> </div>
            <?php endif ?>
        </div>
    </div>
</div>
   
<?php
$js = <<<JS
// get the form id and set the event
$('form#{$model->formName()}').on('beforeSubmit', function(e) {
   var \$form = $(this);
   alert('No se pueden hacer preguntas por los momentos');
}).on('submit', function(e){
    e.preventDefault();
});
JS;
 
// $this->registerJs($js); 