controllers/ArticulosController.php
<?php

namespace app\controllers;
use yii\data\Pagination;

use Yii;
use app\models\Articulos;
use app\models\Preguntas;
use app\models\PreguntasQuery;
use app\models\ArticulosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Categorias;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

// use yii\base\InvalidParamException;
// use yii\web\BadRequestHttpException;
// use yii\data\Pagination;
// use yii\data\ActiveDataProvider
/**
 * ArticulosController implements the CRUD actions for Articulos model.
 */
class ArticulosController extends Controller
{
    public function behaviors()
    {
        return [

        'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'index','preguntas'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['create','index','preguntas','update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [ 'actions' => ['update'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            // $model = new Articulos;
                            $id = $_GET['id'];
                            // $id = $_GET['id'];
                            $model = $this->findModel($id);
              if (Yii::$app->user->isGuest) {
                              return false;
                            }
                            // return Yii::$app->user->identity->getId() == $model->id_usu;
                            return Yii::$app->user->identity->getId() == $model->id_usu;
                        }
                        ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Articulos models.
     * @return mixed
     */
    public function actionIndex()
    {
          $categories = Categorias::find()->select(['id', 'categoria'])->where(['padre' => 0,])->all();
        $query = Articulos::find()->where(['id_usu' => Yii::$app->user->identity->getId()]);
        if (isset($_GET['cat'])) { $query = Articulos::find()->where(['id_cat' => $_GET['cat'], 'id_usu' => Yii::$app->user->identity->getId()]); }
 
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize'=>6]);

        $models = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('index', [
            'categories'=> $categories, 
                                'models'=> $models, 
                                'pages' => $pages
        ]);
    }

    /**
     * Displays a single Articulos model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    { $preguntas= new Preguntas;
      $mpreguntas = Preguntas::find()->where(['id_art' => $_GET['id'],])->all(); 
        // $preguntas->save();
        
        // var_dump($_POST) ;
        if ($preguntas->load(Yii::$app->request->post()) && $preguntas->save() && $preguntas->validate()) {
          Controller::refresh();
        }
        return $this->render('view', [ 'model' => $this->findModel($id), 'preguntas' => $preguntas, 'mpreguntas' => $mpreguntas,
        ]);

    }

    public function actionCreate()
    {   
        $model = new Articulos();
        $categorias = Categorias::find()->asArray()->all();
        $categoria = ArrayHelper::map($categorias, 'id', 'categoria');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->foto1 = UploadedFile::getInstance($model,'foto1')) { if ($model->upload()) { $model->save(); }
                }
          if ($model->foto2 = UploadedFile::getInstance($model,'foto2')) { if ($model->upload2()) { $model->save(); }
                }
            return $this->redirect(['view', 'id' => $model->id]); }
         else {
            return $this->render('create', [
                'model' => $model,
                'categoria'=>$categoria,
            ]);
        }
    }
    /**
     * Creates a new Articulos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

// SELECT * FROM preguntas as P  INNER JOIN articulos as A ON P.id_art = A.id  INNER JOIN user as U ON A.id_usu = U.id WHERE P.id_art = A.id

//SELECT U.username, P.post, C.comment FROM comentarios as C  INNER JOIN post as P ON C.idpost = P.idpost  INNER JOIN usuarios as U ON P.id_usu = U.id WHERE C.idpost = P.idpost



// SELECT c.preguntas, p.articulos, r.user FROM preguntas cINNERJOIN articulos pON c.id = p.id_art INNER JOIN usuarios r ON r.Id = p.id_usu
//SELECT c.comuna, p.provincia, r.region FROM Comunas cINNER JOIN Provincias pON c.idprovincia= p.idprovincia INNER JOIN Regiones r ON r.IdRegion = p.IdRegion
      // $misarticulos = Articulos::find()->select('id')->where(['id_usu' =>Yii::$app->user->identity->getId()])->orderBy('id')->all(); 
      public function actionPreguntas()    { 
      $preguntas = new Preguntas;
// echo "<br><br><br><br><br>";
      // var_dump($_POST['Preguntas']);

      if (isset($_POST['Preguntas'])) {
$model = $this->findPreguntas($_POST['Preguntas']['id']);
            // $model = Preguntas::find($_POST['Preguntas']['id']);
            $model->respuesta = $_POST['Preguntas']['respuesta'];
            $model->save();  
      }
$my=Preguntas::findBySql('select P.id, P.pregunta, P.respuesta from preguntas as P INNER JOIN articulos as A ON P.id_art = A.id where respuesta IS NULL AND id_usu ='.Yii::$app->user->identity->getId())->all();

        return $this->render('preguntas', [
                                // 'mpreguntas'=> $mpreguntas, 
                                'preguntas' => $preguntas,
                                'my' => $my,
        ]);
    }

    /**
     * Updates an existing Articulos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $categorias = Categorias::find()->asArray()->all();
        $categoria = ArrayHelper::map($categorias, 'id', 'categoria');
        $model = $this->findModel($id);
        echo "<br><br><br><br>";

        if (!empty($_POST)) {
          $file = \yii\web\UploadedFile::getInstance($model, 'foto1');
          if ($model->save()) {
              if ($file==null) {
              $fotoa = $model->foto1;
               $model->load(Yii::$app->request->post());
              $model->foto1 =$fotoa;
               $model->save();
            }
            else {
               $model->load(Yii::$app->request->post());
                $rnd= rand(0,9999);
                // $model->foto1 = $rnd.$_POST['Articulos']['foto1'];
              $model->foto1= $rnd.$file->name;
              $model->save();
              $file->saveAs('images/articulos/'.$rnd.$file->name);
              }
            }
          return $this->redirect(['view', 'id' => $model->id]);
        }
        // its better if you relegate such a code to your model class
    // }
    return $this->render('update', ['model'=>$model, 'categoria' => $categoria]);
    }

    /**
     * Deletes an existing Articulos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Articulos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Articulos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Articulos::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
      protected function findPreguntas($id)
    {
        if (($model = Preguntas::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
// use app\widgets\Alert;
use yii\bootstrap\Alert;
use yii\bootstrap\Carousel;
use yii\helpers\Url;
use  yii\helpers\BaseUrl;
AppAsset::register($this);
$this->beginBlock('search');
// ActiveForm::begin();
echo '<form class="navbar-form navbar-left forbusqueda" action=""><div class="form-group boxbusqueda"><input type="text" class="form-control busqueda" placeholder="Buscar Articulos"></div><button style="font-size: 21px; padding: 0px 5px;" class="btn btn-info btn-sm" type="submit"><i class="glyphicon glyphicon-globe"></i></button></form>';
// echo Html::submitButton('Submit', ['class'=> 'btn btn-primary']);
// ActiveForm::end();
$this->endBlock();

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>


<link rel="apple-touch-icon" sizes="57x57" href="images/favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="images/favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="images/favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="images/favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="images/favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="images/favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="images/favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="images/favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="images/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="images/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="images/favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="images/favicon/favicon-16x16.png">
<link rel="manifest" href="images/favicon/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<link type="text/css" href="css/mystyle.css" rel="stylesheet">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

  <div class=" clearfix "> </div>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([

         // <img class="hidden-xs" src="http://placehold.it/150x50&text=Logo" alt="">
        // <img class="visible-xs" src="http://placehold.it/120x40&text=Logo" alt="">    
        'brandLabel' => Html::img('@web/images/logo.svg', ['alt'=>'some', 'class'=>'img-resposive']),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-MP navbar-fixed-top',
        ],
    ]);
    echo $this->blocks['search'];
    $menuItems = [
        // ['label' => 'Home', 'url' => ['/site/index']],
        // ['label' => 'Sobre Nosotros', 'url' => ['/site/about']],
        // ['label' => 'Contact', 'url' => ['/site/contact']],
        // ['label' => Yii::t('app', "Login"), 'items' => $this->blocks['search']],
        // ['label' => 'Vender', 'url' => ['/articulos/create']],
    ];
    if (Yii::$app->user->isGuest) {
       $menuItems[] = ['label' => 'Registro', 'url' => ['/user/registration/register']];
        $menuItems[] = ['label' => Yii::t('app','Inicio Sesion'), 'url' => ['/user/security/login']];
    } else {

        $menuItems[] = [
                        'label' => Yii::t('app','Mi cuenta'),
            'items' => [ 
              [
                'label' => Yii::t('app','Mi Perfil'), 
                'url' => ['/user/settings/account'],
              ],
              [
              'label' => Yii::t('app','Vender'),
              'url' => ['/articulos/create'],
              ],
              [
              'label' => Yii::t('app','Mis Articulos'),
              'url' => ['/articulos/index'],
              ],
              [
              'label' => Yii::t('app','Mis Preguntas'),
              'url' => ['/articulos/preguntas'],
              ],
                [
              'label' => Yii::t('app','Mi Trayectoria'),
              'url' => ['/user/profile/trayectoria', 'id'=> Yii::$app->user->identity->getId()],
              ],
              [
              'label' => Yii::t('app','Cerrar Sesion'),
              // ."(". Yii::$app->user->identity->username .")"
              'url' => ['/user/security/logout'],
              'linkOptions' => ['data-method' => 'post']
              ],
            ],
        ];
        if(Yii::$app->user->identity->isAdmin) {
          $menuItems[] = ['label' => 'admin', 'url' => ['/user/admin/index']];
        }


    }
    echo Nav::widget([
        'options' => ['class' => 'cabeceraboton navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>
  <?php 
  if (Yii::$app->controller->id == 'site') {
      # code...
echo "<br><br><br> ".Carousel::widget([
    'items' => [ 
        Html::img('@web/images/slide/liston.jpg'),
        // Html::img('@web/images/slide/liston1.jpg'),
        Html::img('@web/images/slide/liston2.jpg'),
        Html::img('@web/images/slide/liston3.jpg'),
        Html::img('@web/images/slide/liston4.jpg'),
        // Html::img('@web/images/slide/liston5.jpg'),
          ]
   
]); 

  }

 ?>


<div class=" clearfix " style="height: 67px;"> </div>
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?php //echo Alert::widget() ?>
        <?= $content ?>
    </div>
</div>
<div class=" clearfix "> </div>
<br><br><br><br><br>
<footer class="footer row">
    <!-- <div class=""> -->
        <div class="col-md-6 pull-left "> <p class="copyright"> Copyright &copy;  2015 Mercadopulgas Venezuela  </p></div>
      <!-- <div class="col-md-2"></div> -->
        <div class="col-md-4 impact developer text-right txtblack">
         <!-- <div class="col-md-3 ima pull-right developer"> -->
        Pagina Desarrollada por &nbsp;
        </div>
        <div class="col-md-2" > 
        <?= Html::a( Html::img('@web/images/owlogo.png',['class'=>'img-responsive']), 'http://oteroweb.com.ve') 
        ?> 
        </div>
    <!-- </div> -->
</footer>
<div class="row espaciofooter text-center"> 


</div>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?49gsUhBrrem76tMAt42pfZuCJij94hOY";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->
<?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>